### ISSUE TITLE
Import to Max4Live?

### ISSUE THREAD

**Issue by rotten77** [coffeeshopped/mopho-editor#1]
Hi, is there any way to import to Max4Live? I want to use this great editor inside my Ableton project, but I can't insert it correctly.

**Comment by coffeeshopped** [comment]
I'm sure it could be adapted to Max4Live, but it would be a little work. But, it's open source, so you're welcome to it. ;)

**Comment by rotten77** [comment]
I am trying it, but there is some probem with sharing MIDI ports. I am newbie with M4L, but I am going to solve it :-)

**Comment by coffeeshopped** [comment]
Awesome, good luck with it!
